StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E58D633D7316693}" {
   Id "AER-EditableEntity_Laptop_Name"
   Target_en_us "Laptop (en-us)"
   Target_de_de "Laptop (de-de)"
   MaxLength 28
   Modified 1582882915
   Author "y0014984"
   LastChanged "y0014984"
   Labels {
    300
   }
   SourceFile "{674FF4B085B41FFF}PrefabsEditable/Auto/E_Laptop.et"
   ImageLink "https://bohemiainteractive.sharepoint.com/:i:/r/sites/reforger/translations/Images/E_Laptop.png"
  }
  CustomStringTableItem "{5E58D63336716F97}" {
   Id "AER-Terminal-Headline"
   Target_en_us "armaOS Terminal for Reforger v0.1 (en-us)"
   Target_de_de "armaOS Terminal für Reforger v0.1 (de-de)"
   Modified 1582881115
   Author "y0014984"
   LastChanged "y0014984"
  }
 }
}