StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E58D633D7316693}" {
   Id "AER-EditableEntity_Laptop_Name"
   Target_en_us "Laptop"
   Target_de_de "Laptop"
   MaxLength 28
   Modified 1582988940
   Author "y0014984"
   LastChanged "y0014984"
   Labels {
    300
   }
   SourceFile "{674FF4B085B41FFF}PrefabsEditable/Auto/E_Laptop.et"
   ImageLink "https://bohemiainteractive.sharepoint.com/:i:/r/sites/reforger/translations/Images/E_Laptop.png"
  }
  CustomStringTableItem "{5E5CBE8FEC772F3C}" {
   Id "AER-PowerState-Off"
   Target_en_us "Off"
   Target_fr_fr "Off"
   Target_it_it "Spento"
   Target_de_de "Ausgeschaltet"
   Target_ru_ru "Выкл"
   Target_zh_cn "关"
   Modified 1583146757
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5E5CBE8FE0AC4280}" {
   Id "AER-PowerState-On"
   Target_en_us "On"
   Target_fr_fr "On"
   Target_it_it "Acceso"
   Target_de_de "Eingeschaltet"
   Target_ru_ru "Вкл"
   Target_zh_cn "开"
   Modified 1583146715
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5E5CBE8FEEDECBCC}" {
   Id "AER-PowerState-Standby"
   Target_en_us "Standby"
   Target_fr_fr "Veille"
   Target_it_it "Attesa"
   Target_de_de "Ruhezustand"
   Target_ru_ru "Ожидание (Standby)"
   Target_zh_cn "待机"
   Modified 1583146657
   Author "y0014984"
   LastChanged "y0014984"
  }
  CustomStringTableItem "{5E58D63336716F97}" {
   Id "AER-Terminal-Headline"
   Target_en_us "armaOS Terminal for Reforger v0.1"
   Target_de_de "armaOS Terminal für Reforger v0.1"
   Modified 1582988916
   Author "y0014984"
   LastChanged "y0014984"
  }
 }
}